### ISSUE TITLE
ERROR - ISO8583MessageHandler Couldn't unpack the message since message is not in ISO Standard

### ISSUE THREAD

**Issue by alfarioekaputra** [wso2-extensions/esb-connector-iso8583#5]
hello, 

i try wso2esb connector base on here [Configuring+ISO8583+Connector+Operation](https://docs.wso2.com/display/ESBCONNECTORS/Configuring+ISO8583+Connector+Operation)

when i test the iso with this format 

`<ISOMessage>`
      `<data>`
        `<field id="0">0200</field>`
        `<field id="3">568893</field>`
      `</data>`
`</ISOMessage>`

i get the error 

> ERROR - ISO8583MessageHandler Couldn't unpack the message since message is not in ISO Standard :ISOMessage from pool-27-thread-1 is consumed :0210200000000200000056889300
org.jpos.iso.ISOException: org.jpos.iso.IFA_LLNUM: Problem unpacking field 2 (org.jpos.iso.ISOException: Field length 573 too long. Max: 19) unpacking field=2, consumed=36
       	at org.jpos.iso.ISOBasePackager.unpack(ISOBasePackager.java:265)
       	at org.jpos.iso.ISOMsg.unpack(ISOMsg.java:420)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageHandler.unpackResponse(ISO8583MessageHandler.java:102)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageHandler.clientHandler(ISO8583MessageHandler.java:71)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageHandler.<init>(ISO8583MessageHandler.java:45)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageProducer.packedISO8583Message(ISO8583MessageProducer.java:73)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageProducer.connect(ISO8583MessageProducer.java:39)
       	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
       	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:84)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
       	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:104)
       	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
       	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
       	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
       	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:210)
       	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
       	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:325)
       	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:371)
       	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
       	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)

### how to write standart iso message?

thanks

**Comment by Kanapriya** [comment]
Hi ,
You have to build the standard ISO8583 Messages . For more information follow the following link http://jimmod.com/blog/2011/07/26/jimmys-blog-iso-8583-tutorial-build-and-parse-iso-message-using-jpos-library/

**Comment by alfarioekaputra** [comment]
I have followed the link you mentioned above, but still there are errors

the iso message
`<ISOMessage>`
		`<data>`
			`<field id="0">0200</field>`
			`<field id="3">201234</field>`
			`<field id="4">10000</field>`
			`<field id="7">110722180</field>`
			`<field id="11">123456</field>`
			`<field id="44">A5DFGR</field>`
			`<field id="105">ABCDEFGHIJ 1234567890</field>`
		`</data>`
	`</ISOMessage>`

error message
> ERROR - ISO8583MessageHandler Couldn't unpack the message since message is not in ISO Standard :ISOMessage from pool-27-thread-1 is consumed :0210F22000000210000000000000008000001812345678901234567820123400000001000001107221801234560006A5DFGR021ABCDEFGHIJ 1234567890
org.jpos.iso.ISOException: org.jpos.iso.IFA_LLNUM: Problem unpacking field 2 (org.jpos.iso.ISOException: Field length 20 too long. Max: 19) unpacking field=2, consumed=52
       	at org.jpos.iso.ISOBasePackager.unpack(ISOBasePackager.java:265)
       	at org.jpos.iso.ISOMsg.unpack(ISOMsg.java:420)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageHandler.unpackResponse(ISO8583MessageHandler.java:102)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageHandler.clientHandler(ISO8583MessageHandler.java:71)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageHandler.<init>(ISO8583MessageHandler.java:45)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageProducer.packedISO8583Message(ISO8583MessageProducer.java:73)
       	at org.wso2.carbon.connector.ISO8583.ISO8583MessageProducer.connect(ISO8583MessageProducer.java:39)
       	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
       	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:84)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
       	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:104)
       	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148)
       	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97)
       	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59)
       	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
       	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:210)
       	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
       	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:403)
       	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:151)
       	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)

**Comment by Kanapriya** [comment]
Then it should be in your ISOPackager. I have test it with fresh esb-4.9.0 pavk with proxy https://github.com/wso2-extensions/esb-connector-iso8583/blob/master/src/test/resources/artifacts/ESB/config/proxies/ISO8583/ISO8583.xml  by following this https://docs.wso2.com/display/ESBCONNECTORS/Configuring+ISO8583+Connector+Operation.
It works fine for me.
please find the log 
[2016-09-05 15:36:12,022]  INFO - LogMediator To: /services/ISO8583_Test, MessageID: urn:uuid:97eda030-7944-4d34-8c7f-2ca99af29a27, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><ISOMessage>
  <data>
    <field id="0">0200</field>
    <field id="3">201234</field>
    <field id="4">10000</field>
    <field id="7">110722180</field>
    <field id="11">123456</field>
    <field id="44">A5DFGR</field>
    <field id="105">ABCDEFGHIJ 1234567890</field>
  </data>
</ISOMessage><ISOMessage><data><field id="0">0210</field><field id="3">201234</field><field id="4">000000010000</field><field id="7">0110722180</field><field id="11">123456</field><field id="39">00</field><field id="44">A5DFGR</field><field id="105">ABCDEFGHIJ 1234567890</field></data></ISOMessage></soapenv:Body></soapenv:Envelope>

**Comment by alfarioekaputra** [comment]
hmmm, What tools do you use to send the message and can you send me the jposdef.xml, maybe I have some mistake in my definition, and can i use inbound endpoint [Configuring+ISO8583+Inbound+Operations](https://docs.wso2.com/display/ESBCONNECTORS/Configuring+ISO8583+Inbound+Operations) for Testserver?

**Comment by Kanapriya** [comment]
You can find the jposdef.xml file in https://github.com/wso2-extensions/esb-connector-iso8583/blob/master/src/main/resources/jposdef.xml
No, you can't  use inbound endpoint as the Testserver with current implementation.

**Comment by Kanapriya** [comment]
You can use the inbound as testServer with the following minor changes with inbound and and configuration.

1. You can comment the line in the following class, then build the pom and got the new jar and paste it into the lib directory (remove the previous jar from dropins) https://github.com/wso2-extensions/esb-inbound-iso8583/blob/master/src/main/java/org/wso2/carbon/inbound/iso8583/listening/ConnectionRequestHandler.java#L61
2. Use the following proxy and the following inbound configuration
`<proxy name="ISO8583_Test" startOnLoad="true" trace="disable" transports="https http">
        <description/>
        <target>
            <inSequence>
                <ISO8583.init>
                    <serverHost>localhost</serverHost>
                    <serverPort>5000</serverPort>
                </ISO8583.init>
                <ISO8583.sendMessage/>
                <log level="full"/>
                <respond/>
            </inSequence>
            <outSequence>
                <log/>
                <send/>
            </outSequence>
        </target>
    </proxy>`

`<sequence name="request" onError="fault">
        <log level="full"/>
    </sequence>`

`<inboundEndpoint
        class="org.wso2.carbon.inbound.iso8583.listening.ISO8583MessageConsumer"
        name="custom_listener" onError="fault" sequence="request" suspend="false">
        <parameters>
            <parameter name="sequential">true</parameter>
            <parameter name="inbound.behavior">listening</parameter>
            <parameter name="port">5000</parameter>
        </parameters>
    </inboundEndpoint>`

**Comment by alfarioekaputra** [comment]
what do you mean about "you can't use inbound endpoint as the Testserver with current implementation", because in my case, i have to receive data in ISO format, in my understanding, we use inbound to receive and extract message [https://github.com/wso2-extensions/esb-inbound-iso8583](https://github.com/wso2-extensions/esb-inbound-iso8583), can you give the clue about receiving and extracting iso data.

maybe i ask on the wrong place, sorry about that, maybe we can move to [https://github.com/wso2-extensions/esb-inbound-iso8583](https://github.com/wso2-extensions/esb-inbound-iso8583) issue

**Comment by alfarioekaputra** [comment]
Thanks for the explanation
